package user;

import com.example.api.models.user.UserResponse;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link UserResponse} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserResponseAssert<S extends AbstractUserResponseAssert<S, A>, A extends UserResponse> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserResponseAssert}</code> to make assertions on actual UserResponse.
   * @param actual the UserResponse we want to make assertions on.
   */
  protected AbstractUserResponseAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual UserResponse's age is equal to the given one.
   * @param age the given age to compare the actual UserResponse's age to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserResponse's age is not equal to the given one.
   */
  public S hasAge(int age) {
    // check that actual UserResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting age of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualAge = actual.getAge();
    if (actualAge != age) {
      failWithMessage(assertjErrorMessage, actual, age, actualAge);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserResponse's email is equal to the given one.
   * @param email the given email to compare the actual UserResponse's email to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserResponse's email is not equal to the given one.
   */
  public S hasEmail(String email) {
    // check that actual UserResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting email of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualEmail = actual.getEmail();
    if (!Objects.areEqual(actualEmail, email)) {
      failWithMessage(assertjErrorMessage, actual, email, actualEmail);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserResponse's id is equal to the given one.
   * @param id the given id to compare the actual UserResponse's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserResponse's id is not equal to the given one.
   */
  public S hasId(Long id) {
    // check that actual UserResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Long actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserResponse's name is equal to the given one.
   * @param name the given name to compare the actual UserResponse's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserResponse's name is not equal to the given one.
   */
  public S hasName(String name) {
    // check that actual UserResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserResponse's passport is equal to the given one.
   * @param passport the given passport to compare the actual UserResponse's passport to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserResponse's passport is not equal to the given one.
   */
  public S hasPassport(String passport) {
    // check that actual UserResponse we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting passport of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualPassport = actual.getPassport();
    if (!Objects.areEqual(actualPassport, passport)) {
      failWithMessage(assertjErrorMessage, actual, passport, actualPassport);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
