package user;

import com.example.api.models.user.UserResponse;

/**
 * {@link UserResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractUserResponseAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class UserResponseAssert extends AbstractUserResponseAssert<UserResponseAssert, UserResponse> {

  /**
   * Creates a new <code>{@link UserResponseAssert}</code> to make assertions on actual UserResponse.
   * @param actual the UserResponse we want to make assertions on.
   */
  public UserResponseAssert(UserResponse actual) {
    super(actual, UserResponseAssert.class);
  }

  /**
   * An entry point for UserResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myUserResponse)</code> and get specific assertion with code completion.
   * @param actual the UserResponse we want to make assertions on.
   * @return a new <code>{@link UserResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserResponseAssert assertThat(UserResponse actual) {
    return new UserResponseAssert(actual);
  }
}
